# Something Interesting

## 1 对象的副本、视图

**Numpy中，尤其是在数组运算或数组操作时，返回的结果不是数组的副本就是试图。在Numpy中，所有赋值运算不会为数组和数据中任何元素创建副本。**

In [1]:
import pandas as pd
import numpy as np

In [2]:
a = np.array(range(1, 5))
b = a 

In [3]:
b

array([1, 2, 3, 4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a[2] = 0
b

array([1, 2, 0, 4])

把数组a赋给数组b， 实际上不是为a创建副本，b只不过是调用数组a的另一种方式。事实上，修改a的第三个元素，同样会修改b的第三个元素

**数组切片操作返回的对象只是原数组的试图。列表切片操作得到的是副本。**

In [6]:
c = a[:2]
c

array([1, 2])

In [7]:
a[0] = 0
c

array([0, 2])

如上所见，即使是切片操作得到的结果，实际上仍指向相同的对象。如果想为原数组生成一个完整的副本，从而得到一个不同的数组，使用copy函数即可。

In [8]:
a = np.array([1, 2, 3, 4])
c = a.copy()
c

array([1, 2, 3, 4])

In [9]:
a[0] = 0
c

array([1, 2, 3, 4])

上面的例子中，即使改动数组a的元素，数组c仍保持不变。

## 2 搜索和匹配的比较

术语匹配（matching）指的是术语“模式匹配（pattern-matching）”。在Python中术语中，主要有两种方法完成模式匹配：‘搜索’（searching），即在字符串任意部分中搜索匹配的模式；而“匹配”（matching）是指判断一个字符串是否能从起始处全部或者部分地匹配某个模式。搜索通过search()函数或方法实现，而匹配通过调用match()函数或者方法实现。总之，当涉及模式时，全部使用属于“匹配”；我们按照python如何完成模式匹配的方式来区分“搜索”和“匹配”。——《Python核心编程（第三版）》


#### re模块允许多个线程共享同一个已编译的正则表达式对象，也支持命名子组。

#### re模块的大多数函数也与已经编译好的正则表达式对象(regex object)和正则匹配对象(regex match object)的方法同名并且具有相同的功能。

几乎所有的re模块函数都可以作为regex对象的方法。尽管推荐预编译，但它不是必需的。如果需要编译，就是用编译过的方法；如果不需要编译，就是用函数。不管使用函数还是方法，他们的名字都是一样的。

In [1]:
import re

In [2]:
m = re.match('foo', 'foo')

In [3]:
m

In [4]:
if m is not None:
    m.group()

In [5]:
m.group()

'foo'

In [6]:
if m is not None:
    return m.group()

SyntaxError: 'return' outside function (<ipython-input-6-0b6e9063ebc2>, line 2)

In [7]:
if m is not None:
    print m.group()

foo


#### re模块函数和正则表达式对象的方法      match(pattern, string, flags=0)
尝试使用带有可选的标记的正则表达式的模式来匹配字符串。如果匹配成功，就返回匹配对象；如果失败，就返回None。匹配对象的group()方法能够用于显示那个成功的匹配。

In [8]:
m = re.match('foo', 'bar')
if m is not None:
    print m.group()

In [9]:
m.group()

AttributeError: 'NoneType' object has no attribute 'group'

## 3 函数式编程

**python也提供一些用于函数式编程支持的工具——即在一整组输入（例子是列表）上应用某个函数。**

**这些工具是过滤（`filter`）、映射（`map`）和归纳（`reduce`）**

In [2]:
def even(x):
    return x % 2 == 0
even(3)

False

**返回对象是一份布尔值。这样的函数可以用map应用到整个列表对象：**

In [3]:
map(even, range(10))

[True, False, True, False, True, False, True, False, True, False]

**还可以使用`lambda`（匿名）函数，直接提供一个函数作为`map`的参数：**

In [4]:
map(lambda x: x ** 2, range(10))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

**函数也可以用于过滤列表对象。过滤器返回列表对象中匹配even函数定义的布尔条件的元素：**

In [5]:
filter(even, range(15))

[0, 2, 4, 6, 8, 10, 12, 14]

**归纳（`reduce`）**在我们想要对列表对象的所有元素应用一个函数、返回单个值的时候很有用。

In [7]:
reduce(lambda x, y: x + y, range(10))

45

下面是替代的非函数式实现

In [14]:
def cumsum(l):
    total = 0
    for i in range(l):
        total += i
    return total
cumsum(10)

45

**注意：**  
在python级别上尽可能避免循环被视为“好的习惯”。列表推导和函数式编程工具（reduce、map、filter）提供了编写紧凑（一般来说也更易于理解）的无循环代码的手段。lambda函数也是这方面的强大工具。

## 4 MRO-method resolution order

In [1]:
class D:    #classical class 
    def foo(self):
        print 'class D'

class B(D):
    pass

class C(D):
    def foo(self):
        print 'class C'

class A(B, C):
    pass

In [2]:
f = A()
f

<__main__.A instance at 0x0000000005E9A608>

In [3]:
f.foo()

class D


In [4]:
class D(object):    #new_style class 
    def foo(self):
        print 'class D'

class B(D):
    pass

class C(D):
    def foo(self):
        print 'class C'

class A(B, C):
    pass

In [5]:
f = A()
f

In [6]:
f.foo()

class C


**对于这两种类，在复杂继承结构中，class中的method的调用顺序（MRO）是不同的。**

**classical是深度优先的， new-style是广度优先的。**